-- PostgreSQL schema for productionizing the local-only demonstration.
CREATE TYPE finding_state AS ENUM ('Detected','Needs Validation','Validated','False Positive','Accepted Risk','Remediated','Retest Required','Closed');
CREATE TABLE organizations (id uuid PRIMARY KEY, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE scopes (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), target text NOT NULL, authorized boolean NOT NULL DEFAULT false, local_lab_only boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE assets (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), hostname text NOT NULL, ip inet, environment text NOT NULL, asset_type text NOT NULL, owner text, first_seen timestamptz NOT NULL, last_seen timestamptz NOT NULL, UNIQUE(organization_id,hostname));
CREATE TABLE services (id uuid PRIMARY KEY, asset_id uuid NOT NULL REFERENCES assets(id) ON DELETE CASCADE, port integer NOT NULL, protocol text NOT NULL, status text NOT NULL);
CREATE TABLE technologies (id uuid PRIMARY KEY, asset_id uuid NOT NULL REFERENCES assets(id) ON DELETE CASCADE, name text NOT NULL, version text, confidence numeric(3,2));
CREATE TABLE endpoints (id uuid PRIMARY KEY, asset_id uuid NOT NULL REFERENCES assets(id) ON DELETE CASCADE, url text NOT NULL, http_status integer, authentication_surface boolean NOT NULL DEFAULT false);
CREATE TABLE scan_runs (id uuid PRIMARY KEY, scope_id uuid NOT NULL REFERENCES scopes(id), status text NOT NULL, started_at timestamptz NOT NULL, completed_at timestamptz, tool_provenance jsonb NOT NULL DEFAULT '[]');
CREATE TABLE findings (id uuid PRIMARY KEY, public_id text UNIQUE NOT NULL, asset_id uuid NOT NULL REFERENCES assets(id), endpoint_id uuid REFERENCES endpoints(id), title text NOT NULL, severity text NOT NULL, confidence text NOT NULL, status finding_state NOT NULL DEFAULT 'Detected', evidence jsonb NOT NULL DEFAULT '{}', first_detected timestamptz NOT NULL, last_detected timestamptz NOT NULL);
CREATE TABLE evidence (id uuid PRIMARY KEY, finding_id uuid NOT NULL REFERENCES findings(id) ON DELETE CASCADE, kind text NOT NULL, content jsonb NOT NULL, captured_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE risk_scores (id uuid PRIMARY KEY, asset_id uuid NOT NULL REFERENCES assets(id) ON DELETE CASCADE, score numeric(5,2) NOT NULL CHECK(score BETWEEN 0 AND 100), factors jsonb NOT NULL, calculated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE asset_changes (id uuid PRIMARY KEY, asset_id uuid REFERENCES assets(id), scan_run_id uuid REFERENCES scan_runs(id), change_type text NOT NULL, before_value jsonb, after_value jsonb, observed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE researcher_reviews (id uuid PRIMARY KEY, finding_id uuid NOT NULL REFERENCES findings(id), reviewer_id uuid, decision finding_state NOT NULL, notes text, validation_evidence text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE finding_status_history (id uuid PRIMARY KEY, finding_id uuid NOT NULL REFERENCES findings(id), old_status finding_state, new_status finding_state NOT NULL, changed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE remediation_tasks (id uuid PRIMARY KEY, finding_id uuid NOT NULL REFERENCES findings(id), owner text, status text NOT NULL, target_date date, verification_notes text);
CREATE TABLE reports (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), type text NOT NULL, generated_at timestamptz NOT NULL DEFAULT now(), storage_key text NOT NULL);
CREATE TABLE audit_logs (id bigserial PRIMARY KEY, actor_id uuid, action text NOT NULL, target_type text, target_id uuid, metadata jsonb NOT NULL DEFAULT '{}', occurred_at timestamptz NOT NULL DEFAULT now());
